# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r tests/requirements.txt
  - pip install anybadge

stages:
  - Build
  - Test
  - Deploy

create_badge_svg:
  stage: Build
  script:
    - pip install anybadge
    - commits=$(git rev-list --all --count)
    - anybadge -l commits -v $commits -f commits.svg -c green
  artifacts:
    paths:
      - ./commits.svg

flake8:
  stage: Test
  script:
    - flake8 backend/*.py --statistics --count --max-line-length=120

pylint:
  stage: Test
  allow_failure: true
  script:
    - pylint ./backend/*.py --output-format=text

pages:
  stage: Deploy
  before_script:
    - pip install -r requirements.txt
    - apt-get update -qq && apt-get install -y -qq lftp
  script:
    - make html
    - mkdir /root/.ssh                                # Create .ssh directory
    - chmod 700 /root/.ssh                            # Set permissions
    - touch /root/.ssh/known_hosts                    # Create known_hosts files
    - chmod 600 /root/.ssh/known_hosts                # Set permissions
    - ssh-keyscan -H $FTP_HOST >> /root/.ssh/known_hosts  # Add server to known_hosts, "set sftp:auto-confirm" does not work
    - lftp -e "open sftp://$FTP_HOST; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose build/ /subdomains/doctor/; bye"
    - make clean
  only:
    refs:
      - master
