# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r tests/requirements.txt
  - pip install anybadge

stages:
  - Build
  - Test
  - Deploy

create_badge_svg:
  stage: Build
  script:
    - pip install anybadge
    - commits=$(git rev-list --all --count)
    - anybadge -l commits -v $commits -f commits.svg -c green
  artifacts:
    paths:
      - ./commits.svg

flake8:
  stage: Test
  script:
    - flake8 backend/ --statistics --count --max-line-length=120

pylint:
  stage: Test
  allow_failure: true
  script:
    - pylint ./backend/*.py --output-format=text

pages:
  stage: Deploy
  before_script:
    - apt-get install -y lftp
  script:
    - make html
    - lftp -e "open $FTP_HOST; user $FTP_USERNAME FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose build/ /subdomains/doctor/; bye"
    - make clean
  only:
    refs:
      - master